### ISSUE TITLE
Environment Versions

### ISSUE THREAD

**Issue by narnhold** [akandykeller/TopographicVAE#3]
Could you please share the versions for the requirements you used in the environment.
Unfortunately the experiments do not work with the latest Kordia 0.6.3 version.

**Comment by akandykeller** [comment]
Hi Niclas, certainly. I've just added a conda_list.txt file with versions. It looks like I used Kornia 0.3.0. Please let me know if this doesn't work for you and I will explore implementations which avoid the use of Kornia. Thanks!
